---
name: NASA Poject CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: use Node Js 20
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - run: npm install
      - run: npm run build --prefix client

  