---
name: NASA Poject CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    env: 
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    strategy: 
      matrix:
        node-version: [18.x,19.x,20.x] 
        mongodb-version: ['7.0'] 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: use Node Js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}
      - name: use MongoDB from github actions ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test

  